---
title: _Problems of Philosophy_, Chapter 1
subtitle: Philosophy 101 - Class 07
format:
  clean-revealjs:
    self-contained: true
author:
  - name: Brian Weatherson
    orcid: 0000-0002-0830-141X
    email: weath@umich.edu
    affiliations: University of Michigan
date: 2023-09-19
from: markdown+fancy_lists+raw_html
---

# Bertrand Russell {background-color="#40666e"}

## Biography

- Bertrand Russell was born in 1872 and died in 1970.
- It's weird to think that someone born during Ulysses Grant's first term lived to see the moon landing.
- Very prominent both inside academic philosophy, and also popular with the general public. Growing up our house had several Russell books on the shelves, and while my parents had more books than many others, they weren't academics.

## Breadth

- In philosophy, Russell wrote works that sold lots of copies, and works that have been part of the undergrad curriculum ever since, and more technical works that have been part of the graduate curriculum ever since.
- He was also an important figure in mathematics, playing a crucial role in the development of set theory, and in the formalisation of proof theory. 
- And he was a high profile public figure, especially in anti-war campaigns.
- Despite being literally an aristocrat (he was Lord Russell later in life when his ancestors died), he was imprisoned during World War I for anti-war activities.
- And because he kept on living, he met the Beatles during protests against the Vietnam War.

## Philosophical Views

- Because he lived so long, it's hard to say what his views were; he changed his mind on a lot of things.
- Indeed, he would reject a lot of the views in this book within years of writing it.
- _Problems_ is in many ways a reaction to the philosophy of the generation before Russell, and the generation after him convinced him that his rejection wasn't complete enough.
- So don't think this is telling you what philosophers think; it's saying what one philosopher thought at one time.

# Idealism and Realism {background-color="#40666e"}

## Background: Idealism

- The background to the book is that when it was written, most British philosophers believed in a doctrine called **idealism**.
- This isn't a political view; it's not like they were proto-Bernie Sanders supporters with strong political ideals.
- It's derived from **idea**, not **idealism**.
- Idealism, _in this context_, is the view that the world is fundamentally mental.

## Versions of Idealism

- Everything is an idea in the mind of God.
- The physical building blocks of the world (sub-atomic particles), have mental properties.
- Facts about the world are constituted by human ideas. If a tree falls in the forest and no one hears it, it doesn't make a sound, and if no one walks that way, it didn't even fall.

## Alternative View: Realism

- One aim of this book is to set out and defend **realism**.
- Realism, _in this context_, is the view that there is a mind-independent physical reality, and we can come to know quite a lot (but not everything!) about it.

. . .

- Another aim of the book is to argue against idealism. And we're mostly going to skip those parts; they aren't that interesting unless you antecedently are tempted by idealism. (As Russell himself was through about 1898; he's criticising his own youthful views here.)

# Alternative Metaphysics {background-color="#40666e"}

## Pragmatism

In America at the time a rival view known as **pragmatism** was being developed. This term covers a wide range of views, but the general idea is that knowledge about the world is closely tied with acting in the world.

- Pragmatists thought that both realists and idealists were mistaken, because whether it turns out that tables are fundamentally made of quantum waves or divine ideas makes no difference to how we should interact with the table.

## Positivism

In continental Europe, especially in Austria, a similar view called **positivism** was being developed.

- The key positivist idea was that a claim is meaningful only to the extent that some experiment could provide evidence for or against it.
- The positivists thought that the things realists and idealists said were literally _meaningless_, as if they were grunting.

# Color Variation

## Color Realism

If colors are real, they presumably are really something physical.

We know very roughly what features of objects cause color sensations in creatures like us: their reflectance properties.

E.g., red objects reflect light of wavelength around 620 to 750nm, and absorb light of other wavelengths. Blue objects, on the other hand, reflect light with much shorter wavelengths, around 420 to 500nm.

## Color Realism

So that's what a simple realist view would say about color.

To be red just is to have the property that you predominantly reflect light of a certain wavelength, in normal circumstances.

. . .

That last phrase looks like it will cause trouble - what's a normal circumstance. And it does indeed cause trouble.

## Aim For Rest of Class

- Go over some puzzles for color realism.
- Introduce you to a few facts about color which are philosophically and psychologically interesting.
- Go over some ways of raising doubts about realism in a domain that might generalise to doubts about other kinds of realism.

## An Experiment

This might all end very badly for the professor, but I'm going to run a little in class experiment.

For the next few slides I'm going to have colored backgrounds on the slides. The colors will all be in the vicinity of blue.

## &nbsp; {background-color="#0000FF"}

Is the background to this slide:

| (A) Purple-ish blue
| 
| (B) Just blue
| 
| (C) Green-ish blue

## &nbsp; {background-color="#008888"}

Is the background to this slide:

| (A) Purple-ish blue
| 
| (B) Just blue
| 
| (C) Green-ish blue

## &nbsp; {background-color="#4400BB"}

Is the background to this slide:

| (A) Purple-ish blue
| 
| (B) Just blue
| 
| (C) Green-ish blue

## &nbsp; {background-color="#001FE0"}

Is the background to this slide:

| (A) Purple-ish blue
| 
| (B) Just blue
| 
| (C) Green-ish blue

## &nbsp; {background-color="#0F00F0"}

Is the background to this slide:

| (A) Purple-ish blue
| 
| (B) Just blue
| 
| (C) Green-ish blue

## &nbsp; {background-color="#0050BF"}

Is the background to this slide:

| (A) Purple-ish blue
| 
| (B) Just blue
| 
| (C) Green-ish blue

## &nbsp; {background-color="#3000CF"}

Is the background to this slide:

| (A) Purple-ish blue
| 
| (B) Just blue
| 
| (C) Green-ish blue

## Results

At this time I'm writing these slides, I don't know how these experiments will go. As you can probably tell, I'm not exactly an expert in experiment design.

But when people who are experts in experiment design run experiments like this, what they find is there is a fair bit of variation in what people take to be 'just blue'.

. . .

And, the variation isn't completely random; it is correlated with gender.

## Metamers

To understand what a metamer is, we need a crash course in how human color vision works.

This is going to be incredibly rough - if an actual scientist tells you something other than it, believe them.

And it's only for neurologically/anatomically typical humans. Which is most but definitely not all of us.

## Metamers

Humans (typically) perceive colors because they have three kinds of sensors in their eyes that are sensitive to light of different wavelengths.

With only some violence to the facts, we can think of these as red-detectors, green-detectors, and blue-detectors.

## Metamers

Of course we can perceive many more colors than three. 

And we don't perceive all other colors as mixtures.

Yellow doesn't look like a mix of red/green/blue in some proportions, the way that purple kind of does.

That's because the brain does quite a lot with the signals from these three detectors subconsciously.

## Metamers

But still, there are only three of the detectors.

And that means that two light sources with very different characteristics can trigger each of the detectors to the same amount.

1. A pure yellow light, around 575nm.
2. A mix of blue light, green light, and red light, each at the level that the yellow light triggers our three detectors.