---
title: Argument Forms
subtitle: Philosophy 101 - Class 03
format:
  clean-revealjs:
    self-contained: true
author:
  - name: Brian Weatherson
    orcid: 0000-0002-0830-141X
    email: weath@umich.edu
    affiliations: University of Michigan
date: 2023-09-05
bibliography: refs.bib
from: markdown+fancy_lists+raw_html
---

# Validity and Form {background-color="#40666e"}

## Sentence Letters

### A useful shorthand

We're going to use $X$ and $Y$ to stand for possible sentences.

So $X$ might be _Brian had bacon and eggs for breakfast_, or _There is a T-Rex on the diag_, or _Seven plus five is twelve_, or any other sentence.

## Combining Sentences

### The mortar of logic

And one of the basic things you do in logic is think about sentences that are built from relatively simple sentences like those. In particular, we're going to talk a little about these four types of sentences.

- $X$ and $Y$.
- $X$ or $Y$.
- If $X$ then $Y$.
- Not $X$.

## Simple Cases of Validity

### From wholes to parts of and-sentences

::: columns
::: {.column width="45%"}
**Argument Form**

1. $X$ and $Y$
C.  $X$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

:::

::: {.column width="45%"}
Is this valid no matter what $X$ and $Y$ are?

A.  Yes
B.  No

:::
:::

## Simple Cases of Validity

### From wholes to parts of and-sentences

::: columns
::: {.column width="45%"}
**Argument Form**

1. $X$ and $Y$
C.  $X$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

:::

::: {.column width="45%"}
Yes! (I guess that's in the title)

The premise says that both $X$ and $Y$ are true, and that guarantees that $X$ is true.

:::
:::

## Simple Cases of Invalidity

### From parts to wholes of and-sentences

::: columns
::: {.column width="45%"}
**Argument Form**

1. $X$
C.  $X$  and $Y$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

:::

::: {.column width="45%"}
Is this valid no matter what $X$ and $Y$ are?

A.  Yes
B.  No

:::
:::

## Simple Cases of Invalidity

### From parts to wholes of and-sentences

::: columns
::: {.column width="45%"}
**Argument Form**

1. $X$ and $Y$
C.  $X$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

:::

::: {.column width="45%"}
No! (Also in the title)

But the way we tell that is more interesting.

:::
:::

## Showing that a Form is Invalid

### Look for a clearly bad instance

To show that an argument form is invalid, what we do is find values for $X$, $Y$, and any other sentences there are, that make the premises true and the conclusion not true.

In this case the following will work:

- $X$ is _Brian came to work today_.
- $Y$ is _Brian rode a T-Rex this morning_.

---

::: columns
::: {.column width="45%"}
**Argument One**

1. If $X$ then $Y$
2. $X$
C.  $Y$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Two**

1. If $X$ then $Y$
2. $Y$
C.  $X$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Which of these must be valid no matter what $X$ and $Y$ are?

A.  Both One and Two.
B.  Just One.
C.  Just Two.
D.  Neither One nor Two.

:::
:::

---

::: columns
::: {.column width="45%"}
**Argument One**

1. If $X$ then $Y$
2. $X$
C.  $Y$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Two**

1. If $X$ then $Y$
2. $Y$
C.  $X$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Which of these must be valid no matter what $X$ and $Y$ are?

A.  Both One and Two.
B.  [**Just One**]{.bg style="--col: #90EE90"}.
C.  Just Two.
D.  Neither One nor Two.

:::
:::

---

::: columns
::: {.column width="45%"}
**Argument One**

1. If $X$ then $Y$
2. $X$
C.  $Y$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Two**

1. If $X$ then $Y$
2. $Y$
C.  $X$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Hopefully it's clear that **Argument One** is valid.

If you tell me that if $X$ is true, so is $Y$, and you tell me that $X$ is in fact true, hard to know what more conclusive reason you could give for $Y$.

:::
:::

## Argument Two

We need to find an instance where the premises are true, ideally that they are clearly true, and that the conclusion is not true.

. . .

Here's one possibility.

1. If Brian is in Columbus, Ohio, then he is not in New York City.
2. Brian is not in New York City.
C.  Brian is in Columbus, Ohio. \ \ \ \ \ 

---

::: columns
::: {.column width="45%"}
**Argument Three**

1. If $X$ then $Y$
2. $X$ is not true
C.  $Y$ is not true \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Four**

1. If $X$ then $Y$
2. $Y$ is not true
C.  $X$ is not true \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Which of these must be valid no matter what $X$ and $Y$ are?

A.  Both Three and Four.
B.  Just Three.
C.  Just Four.
D.  Neither Three nor Four.

:::
:::

---

::: columns
::: {.column width="45%"}
**Argument Three**

1. If $X$ then $Y$
2. $X$ is not true
C.  $Y$ is not true \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Four**

1. If $X$ then $Y$
2. $Y$ is not true
C.  $X$ is not true \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  


:::

::: {.column width="45%"}
Which of these must be valid no matter what $X$ and $Y$ are?

A.  Both Three and Four.
B.  Just Three
C.  [Just Four]{.bg style="--col: #90EE90"}.
D.  Neither Three nor Four.

:::
:::

## Argument Three

We need to find an instance where the premises are true, ideally that they are clearly true, and that the conclusion is not true.

. . .

Here's one possibility.

1. If Brian is in Detroit, then he is in Michigan.
2. Brian is not in Detroit.
C.  Brian is not in Michigan. \ \ \ \ \

## Argument Four

This one is a bit trickier, but here's the rough reasoning.

- A valid argument means the following is impossible: true premises, not true conclusion.
- Assume we have true premises, false conclusion. So it's not true that $X$ is not true.
- That means it's true that $X$.
- And it's true that If $X$ then $Y$.
- Putting those things together $Y$ must be true, but the second premise says it is not true, so what we assumed is impossible.

## Don't Switch Things Around

### Perhaps the most common logical misstep

I've been going over these a bit slowly because it is one of the most common slips in practice.

In these cases, arguments that can lead to absurd conclusions look a lot like arguments that are valid.

They just involve switching some letters around.

That turns out to be one of the most common forms of slip-ups.

# Parts of Sentences {background-color="#40666e"}

## Subject and Predicate

### The two main parts of a sentence

The simplest sentences say that a particular object has a particular feature. Examples include:

- Brian writes.
- Socrates is mortal.
- Squid is a cat.
- The University of Michigan is large.

## Subject and Predicate

### The two main parts of a sentence

In any of these cases, we say the object is the **subject** of the sentence, and the term expressing the feature is the **predicate**.

:::{.incremental}
- The category predicate cross-cuts familiar grammatical categories.
- Verbs and verb phrases can be predicates, as in _Brian **writes**_.
- Adjectives and adjectival phrases can can be predicates, as in _The University of Michigan **is large**_.
- And nouns and (especially) noun phrases can be predicates, as in _Squid **is a cat**_.
:::

## Predicates

### Ways things can be

In general, a subject-term picks out a thing, and a predicate is used to pick out a way it can be.

By tradition, in formal languages we use lower case letters (usually starting at $a$) for subjects, and upper case letters (usually starting at $F$) for predicates.

So our simple sentences will all be of the form $a$ _is_ $F$.

Don't worry about remembering these details yet; I'm putting them here largely as shorthand for the next few slides.

## Quantified Sentences

### Saying how all and some things are

Sentences don't need any individual subject.

Given two predicates, $F$ and $G$, we can put together the following two important sentence types:

1. All $F$s are $G$s.
2. Some $F$s are $G$s.

## Quantified Sentences

### Saying how all and some things are

For example, given the predicates _is a cat_ and _is happy_, we can form the sentences:

1. All cats are happy.
2. Some cats are happy.

---

::: columns
::: {.column width="45%"}
**Argument Five**

1. All $F$s are $G$s
2. $a$ is $F$
C.  $a$ is $G$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Six**

1. All $F$s are $G$s
2. $a$ is $G$
C.  $a$ is $F$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Which of these must be valid no matter what $a$, $F$ and $G$ are?

A.  Both Five and Six.
B.  Just Five.
C.  Just Six.
D.  Neither Five nor Six.

:::
:::

---

::: columns
::: {.column width="45%"}

**Argument Five**

1. All $F$s are $G$s
2. $a$ is $F$
C.  $a$ is $G$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Six**

1. All $F$s are $G$s
2. $a$ is $G$
C.  $a$ is $F$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Which of these must be valid no matter what $a$, $F$ and $G$ are?

A.  Both Five and Six.
B.  [**Just Five**]{.bg style="--col: #90EE90"}.
C.  Just Six.
D.  Neither Five nor Six.

:::
:::

---

::: columns
::: {.column width="45%"}
**Argument Five**

1. All $F$s are $G$s
2. $a$ is $F$
C.  $a$ is $G$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Six**

1. All $F$s are $G$s
2. $a$ is $G$
C.  $a$ is $F$ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Hopefully it's clear that **Argument Five** is valid.

If you tell me that everything that has feature $F$ also has feature $G$, and this thing $a$ has feature $F$, then $a$ better also have feature $G$.

:::
:::

## Argument Six

We need to find an instance where the premises are true, ideally that they are clearly true, and that the conclusion is not true.

. . .

Here's one possibility.

1. All Michiganders are Americans.
2. Joe Biden is an American.
C.  Joe Biden is a Michigander. \ \ \ \ \ 


---

::: columns
::: {.column width="45%"}
**Argument Seven**

1. All $F$s are $G$s
2. All $G$s are $G$s
C.  All $F$s are $H$s \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Eight**

1. Some $F$s are $G$s
2. Some $G$s are $G$s
C.  Some $F$s are $H$s \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Which of these must be valid no matter what $a$, $F$ and $G$ are?

A.  Both Seven and Eight.
B.  Just Seven.
C.  Just Eight.
D.  Neither Seven nor Eight.

:::
:::

---

::: columns
::: {.column width="45%"}
**Argument Seven**

1. All $F$s are $G$s
2. All $G$s are $G$s
C.  All $F$s are $H$s \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

**Argument Eight**

1. Some $F$s are $G$s
2. Some $G$s are $G$s
C.  Some $F$s are $H$s \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 


:::

::: {.column width="45%"}
Which of these must be valid no matter what $a$, $F$ and $G$ are?

A.  Both Seven and Eight.
B.  [**Just Seven**]{.bg style="--col: #90EE90"}.
C.  Just Eight.
D.  Neither Seven nor Eight.

:::
:::

## Argument Seven

Intuitively, this is valid for the following reason.

- Think about any thing whatsoever that is $F$.
- By premise 1, it is $G$.
- And then by premise 2, it is $H$.
- And so for any thing that is $F$, it is $H$.
- Which is what the conclusion says.

## Argument Seven

### Drawing it Out

We could also do this with Venn Diagrams, in case it isn't already clear.

## Argument Eight

Here we need to come up with an example of $F$, $G$ and $H$ that makes the premises both true and the conclusion false.

Can you think of any?

## Argument Eight

Here's one that I think works.

- $F$ = City in the USA
- $G$ = City that I have visited
- $H$ = City in Canada

## Argument Eight

1. Some city in the USA has been visited by me. (True, since I've visited Ann Arbor.)
2. Some city I've visited is in Canada. (True, since I've visited Toronto.)
C.  Some city in the USA is in Canada. (False, cities are within countries.)

## Argument Eight

We can also do this with Venn Diagrams, though I'll leave that as an exercise.

# For Next Time {background-color="#40666e"}

## Inductive Arguments

Most arguments we use in everyday life are not valid.

Next time we'll move to a different book for a short introduction to inductive arguments.

We're only looking at 6 pages of the book, even though it's hundreds of pages long.

The other parts are actually useful for what we'll do next week, but I'm not assigning them.

I'm just grateful that we can get parts of books without buying all of them!