---
title: _Dialogues Concerning Natural Religion_, Parts I and II
subtitle: Philosophy 101 - Class 13
format:
  clean-revealjs:
    self-contained: true
author:
  - name: Brian Weatherson
    orcid: 0000-0002-0830-141X
    email: weath@umich.edu
    affiliations: University of Michigan
date: 2023-10-10
from: markdown+fancy_lists+raw_html
---

# The Very Big Picture {background-color="#40666e"}

## The Characters

**Demea** is a fairly traditional theist. Though note that even he thinks that it is possible to argue for God’s existence.

**Cleanthes** is a fashionable (for the 18th century) theist. He gives empirical arguments for God.

**Philo** is a playful sceptic. He often appears to agree with Demea.

## Publication Details

Although the dialogues do not explicitly  take sides in religious disputes, Hume did not feel comfortable publishing them in his lifetime.

They were published posthumously in 1779.

Hume lived 1711-1776.

## Hume’s Dialogues

Hume’s language, and syntax, is a product of his time.

Jonathan Bennett has produced a translation of the work from Hume’s version of English into a more modern idiom.

This is linked on the webpage; I'll primarily reference the original, but it might be worth seeing what a 'modern' translation looks like.

## A Priori and A Posteriori

The usage of these terms is a little different today than in Hume’s time.

An a priori argument is an argument from first principles, e.g. an argument in mathematics.

An a posteriori argument is an argument from empirical observation, e.g. an argument in biology.

## A Priori and A Posteriori

Hume uses a posteriori the same way.

But in his time, the “argument a priori”, literally argument from what came before, referred to what we call the cosmological argument.

This is the argument that everything has a cause, so the universe must have a cause, and that is God.

## A Priori and A Posteriori

The argument a posteriori relies much more on evidence of what the actual world is like.

What has come after creation seems so ordered, so we might think designed, that we are justified in believing in a designer.

And that’s God.

## Inductive Reasoning

Often our reasoning takes us beyond things we directly observe.

For instance most of us believe the snow on Mt Everest is cold, even if we haven’t felt that particular snow.

One reason is that we have lots of past experience with snow, and it has generally been cold.

## Inductive Reasoning

There are three main types of inductive argument:

1. Enumerative Induction
2. Analogy
3. Inference to the Best Explanation

There could be others, e.g., testimonial reasoning, or causal reasoning, but lots of people, including I think Hume, are taking these to be fundamental.

## Inductive Reasoning

We've talked about all these before, so I'll be brief here.

1. **Enumerative Induction** is projecting a pattern (e.g., that snow is cold) from observed instances to unobserved instances.
2. **Analogy** is inferring that unobserved things that are analogous to existing observed things in some respects are alike in other respects.
3. **Inference to the Best Explanation** is believing the best explanation of the observed data.

# Design Arguments {background-color="#40666e"}

## Design Argument

The short version of the design argument looks like this.

1. The world has lots of features that seem like they are designed.
2. Therefore, the world has a designer.
3. The designer of the world would be a god.
4. Therefore, a god exists.
5. Therefore, God, of the great monotheistic religions, exists.

## Design Argument

The conclusion is very much not that one of Judaism, Christianity, or Islam is correct.

But it is that something like one of those religions, with one capital-G God, exists.

We are not going to get into whether this argument best supports one of those three religions.

But we will talk about whether it's a good argument for **monotheism** as opposed to **polytheism**.

## Design Argument or Arguments

There are many ways that the design argument has been phrased.

- Some of these make it sound like an argument by analogy.
- Some of these make it sound like an inference to the best explanation.
- We’ll look at both arguments.

## Design Argument (Analogy)

1. Artifacts that serve a purpose are designed.
2. The universe serves a purpose.
3. So by analogy to these artifacts it is designed.

## Design Argument (Analogy)

- This doesn’t quite get us God.
- We can get a bit closer to God’s existence (or at least to gods' existences) with a trivial step.
- Designed things have designers.
- So it has a designer.
- Who is this designer?

## Design Argument (IBE)

- Things we see, especially living creatures, have complex parts that fit together well.
- The best explanation of this is that they have a benevolent designer.
- Hence that designer, i.e. God, exists.

## Poll

Not entirely obvious question, and this is a poll not a quiz.

When Cleanthes gives the design argument, is he giving:

A.  The analogy version
B.  The IBE version
C.  Both of them
D.  Something different

## Design Arguments

These two arguments overlap, but on inspection they may turn out to be very different arguments.

In particular, there are different objections that we might make to the arguments

## Four Objections

- **Weak analogy**: The universe is not like artifacts
- **Regress**: Who designed God?
- **Nature of God**: This doesn’t establish God’s goodness
- **Alternative explanations**: The universe could have ‘generated’

## Design Argument

- The weak analogy objection is strictly an objection to the analogy argument.
- And the alternative explanation point is primarily an objection to the IBE argument.

## Design Argument

At least at first, it seems Hume’s primary focus is the analogy. We'll see if this stays as we move along.

He has Cleanthes run this argument, and Philo and Demea respond to it.

## Cleanthes' Inferences

Cleanthes makes further inferences:

1. That designer is God.
2. Since designers we see are human, by analogy God is similar to humans. (This is true, at least as I understand them, in the three great monotheistic religions I mentioned. But you could imagine a monotheistic religion that rejected it, like the kind of deism popular in the American colonies.)

## Demea’s Objections

First he objects to the similarity between God and humans.

This is surprising because, as I said, I thought the idea that man was made in God’s image was a fairly standard theistic belief.

Surprisingly, Demea is strongly opposed to this conclusion.

He insists that God is infinite and not at all like humans.

Now Demea is a made up character, but in other respects he is fairly orthodox theist.

## Demea’s Objections

This argument gives us a probability that God exists, not a certainty.

This is correct, but we shouldn’t make too much of it.

It’s only probable in Demea’s sense that the next snow you see will be cold.

## Kind of Designer

Philo also objects to the analogy to humans.

It is unreasonable to believe we are the only kind  of intelligent life in the universe.

These other intelligences will also design some things.

So God could resemble them.

## Other Design Objections

This isn’t yet an objection to a design argument for theism.

Theism as such is consistent with God being more like a whale than a human.

Or more like a Martian.

Philo backs away from the claim about life on other planets by noting the variety of life on earth.

##  For Next Time

- Read chapter 3 of Hume.
- We’ll look at the Weak Analogy objection.
- Philo has two goes at presenting this objection, after Cleanthes seems to convince him that the first pass doesn’t work.
